"""JSONL session persistence — /resume, /fork, /compact backing store.

The conftest ``_isolated_config_dir`` fixture points ``CAIRN_CONFIG_DIR`` at a
per-test ``tmp_path``, so ``sessions_dir()`` resolves under it without any
extra monkeypatching. Round-trip proofs use the singleton
``ModelMessagesTypeAdapter`` against fixtures built from real ``ModelMessage``
subclasses — the same serialization path the live ``Session.iter_turn`` hook
uses, so a green suite means the on-disk format is load-bearing correct.
"""

from __future__ import annotations

import json

import pytest
from pydantic_ai.messages import (
    ModelMessagesTypeAdapter,
    ModelRequest,
    ModelResponse,
    TextPart,
    UserPromptPart,
)
from pydantic_ai.models.test import TestModel

from cairn.core.paths import sessions_dir
from cairn.orchestration.session import COMPACTION_PROMPT, Session
from cairn.storage import sessions as store
from cairn.storage.db import Database


def _pair() -> list:
    """A canonical [ModelRequest, ModelResponse] pair for round-trip tests."""
    return [
        ModelRequest(parts=[UserPromptPart(content="hi")]),
        ModelResponse(parts=[TextPart(content="hello")]),
    ]


def test_save_header_append_load_round_trip():
    """save_header + append_turn + load returns a list == the input."""
    sid = "roundtrip01"
    store.save_header(sid, model="test-model", prompt="hi", turns=2)
    msgs = _pair()
    store.append_turn(sid, msgs)

    loaded = store.load(sid)
    assert len(loaded) == 2
    assert [type(m).__name__ for m in loaded] == ["ModelRequest", "ModelResponse"]
    # Direct == per SERIALIZE map: ModelMessagesTypeAdapter round-trip preserves
    # content (timestamps are regenerated by validate, so we compare content).
    assert loaded[0].parts[0].content == "hi"
    assert loaded[1].parts[0].content == "hello"


def test_append_turn_writes_one_line_per_message():
    """File has exactly 1 + N lines (header + one per message)."""
    sid = "linecount01"
    store.save_header(sid, model="m", prompt="p", turns=3)
    store.append_turn(sid, [*_pair(), ModelResponse(parts=[TextPart(content="more")])])

    path = sessions_dir() / f"{sid}.jsonl"
    lines = path.read_text(encoding="utf-8").splitlines()
    assert len(lines) == 1 + 3  # header + 3 messages
    header = json.loads(lines[0])
    assert "header" in header
    for line in lines[1:]:
        obj = json.loads(line)
        assert "msg" in obj


def test_list_sessions_ordering_newest_first():
    """list_sessions() returns newest-first by created_at."""
    # Direct file writes for deterministic timestamps (no real-clock race).
    sessions = sessions_dir()
    sessions.mkdir(parents=True, exist_ok=True)
    older = {
        "header": {
            "session_id": "older01",
            "model": "m",
            "created_at": "2026-01-01T00:00:00+00:00",
            "prompt": "old",
            "turns": 1,
        }
    }
    newer = {
        "header": {
            "session_id": "newer01",
            "model": "m",
            "created_at": "2026-07-01T00:00:00+00:00",
            "prompt": "new",
            "turns": 1,
        }
    }
    (sessions / "older01.jsonl").write_text(json.dumps(older) + "\n", encoding="utf-8")
    (sessions / "newer01.jsonl").write_text(json.dumps(newer) + "\n", encoding="utf-8")

    metas = store.list_sessions()
    assert [m.session_id for m in metas] == ["newer01", "older01"]


def test_malformed_lines_skipped_good_survive():
    """load() skips malformed lines, returns the good messages, never raises."""
    sid = "mixed01"
    store.save_header(sid, model="m", prompt="p", turns=2)
    store.append_turn(sid, _pair())
    # Append two malformed lines directly (simulating a partial/corrupt write).
    path = sessions_dir() / f"{sid}.jsonl"
    with path.open("a", encoding="utf-8") as f:
        f.write("not json at all\n")
        f.write('{garbage\n')

    loaded = store.load(sid)
    assert len(loaded) == 2  # only the two good messages survived
    assert loaded[0].parts[0].content == "hi"


def test_list_sessions_skips_corrupt_header():
    """A file with a corrupt first line is omitted from list_sessions, not crashed."""
    sid_good = "good01"
    store.save_header(sid_good, model="m", prompt="p", turns=1)
    # A second file with a broken header line.
    (sessions_dir() / "broken01.jsonl").write_text("{not json\n", encoding="utf-8")

    metas = store.list_sessions()
    ids = {m.session_id for m in metas}
    assert "good01" in ids
    assert "broken01" not in ids


def test_load_missing_session_raises_file_not_found():
    """load() of an absent file raises FileNotFoundError (caught by _cmd_resume)."""
    with pytest.raises(FileNotFoundError):
        store.load("does-not-exist-9999")


async def test_compact_history_shape(fake_settings):
    """compact() leaves history = [ModelRequest(COMPACTION_PROMPT), ModelResponse(summary)].

    Uses TestModel so no network — the summarization turn is exactly two
    messages, and the slice self.history[n_before:] captures exactly that pair.
    """
    reg = __import__("cairn.execution.registry", fromlist=["PluginRegistry"]).PluginRegistry()
    session = Session(
        settings=fake_settings,
        registry=reg,
        model=TestModel(custom_output_text="<summary>"),
        db=Database(fake_settings.data_dir / "cairn.db"),
    )
    # Seed history with a prior turn so compact() has something to summarize.
    session.history = [
        ModelRequest(parts=[UserPromptPart(content="investigate example.com")]),
        ModelResponse(parts=[TextPart(content="prior findings")]),
    ]
    try:
        before, after = await session.compact()
    finally:
        await session.aclose()

    assert before == 2  # the seeded pair
    assert after == 2  # the compaction turn
    assert [type(m).__name__ for m in session.history] == ["ModelRequest", "ModelResponse"]
    req = session.history[0]
    resp = session.history[1]
    assert req.parts[0].content == COMPACTION_PROMPT
    assert resp.parts[0].content == "<summary>"


def test_fork_snapshot_new_id_writes_full_history(fake_settings):
    """fork_snapshot() writes the full history under a fresh id; load() round-trips."""
    reg = __import__("cairn.execution.registry", fromlist=["PluginRegistry"]).PluginRegistry()
    session = Session(
        settings=fake_settings,
        registry=reg,
        model=TestModel(),
        db=Database(fake_settings.data_dir / "cairn.db"),
    )
    session.history = _pair()
    try:
        new_id = session.fork_snapshot()
        assert new_id != session.session_id
        loaded = store.load(new_id)
        assert len(loaded) == 2
        assert loaded[0].parts[0].content == "hi"
        assert loaded[1].parts[0].content == "hello"
    finally:
        session.close()


async def test_persist_appends_on_successful_turn(fake_settings):
    """A persist=True Session writes header + turn messages on a successful ask()."""
    from cairn.execution.base import BasePlugin, Entity, PluginInput, PluginOutput
    from cairn.execution.registry import PluginRegistry

    class _In(PluginInput):
        pass

    class _Out(PluginOutput):
        pass

    class _EchoPlugin(BasePlugin):
        name = "echo_for_persist_test"
        category = "identity"
        requires_key = None
        input_model = _In
        output_model = _Out
        __doc__ = "fake plugin for persist test"

        async def run(self, inp, ctx):  # type: ignore[override]
            return _Out(
                source="echo_for_persist_test",
                summary_markdown="ok",
                entities=[Entity(type="ip", value="203.0.113.1")],
            )

    reg = PluginRegistry()
    reg.register(_EchoPlugin())
    session = Session(
        settings=fake_settings,
        registry=reg,
        model=TestModel(call_tools=["echo_for_persist_test"], custom_output_text="done"),
        db=Database(fake_settings.data_dir / "cairn.db"),
        persist=True,
    )
    try:
        await session.ask("look up 203.0.113.1")
    finally:
        await session.aclose()

    path = sessions_dir() / f"{session.session_id}.jsonl"
    assert path.exists(), "persist=True session should have written a JSONL file"
    lines = path.read_text(encoding="utf-8").splitlines()
    header = json.loads(lines[0])["header"]
    assert header["model"] == session.model_name
    assert header["prompt"] == "look up 203.0.113.1"
    # Each remaining line is a {"msg": ...} from new_messages().
    assert len(lines) >= 2  # header + at least the request/response pair
    for line in lines[1:]:
        assert "msg" in json.loads(line)
    # load() returns the messages pydantic-ai produced this turn.
    loaded = store.load(session.session_id)
    assert ModelMessagesTypeAdapter.validate_python(loaded) == loaded  # type: ignore[arg-type]
    assert len(loaded) == len(lines) - 1  # header excluded
